### ISSUE TITLE
SSL certificate not valid on http://techytest23.000webhostapp.com

### ISSUE THREAD

**Issue by claytonfarrugia** [Dame2Dolla/TechyDev#10]
![image](https://user-images.githubusercontent.com/124443558/221429670-089542fb-1502-41e3-9fc3-8de43e7231f3.png)

**Comment by claytonfarrugia** [comment]
this was automatically fixed when we rehosted our website.

**Comment by Patrick-Frendo** [comment]
Opened in error.
