### ISSUE TITLE
000Webhost cannot connect to Database via API.

### ISSUE THREAD

**Issue by Patrick-Frendo** [Dame2Dolla/TechyDev#12]
![image](https://user-images.githubusercontent.com/16851267/221438912-22f3fff0-87c0-41d4-a2c3-9a7c1aee6842.png)

While implementing  mitigations with @claytonfarrugia. Website worked as intended however after reseting Student password_count column value website stopped working. 

![image](https://user-images.githubusercontent.com/16851267/221439012-52612b42-62ea-4f45-a9a9-f4fef93da9c9.png)

**Comment by claytonfarrugia** [comment]
We resetted the website. thanks @Patrick-Frendo for collaborating with me to find a solution

![image](https://user-images.githubusercontent.com/124443558/221439362-182154bf-9c4d-42a9-91ef-86a864ba2066.png)

**Comment by Patrick-Frendo** [comment]
Solution was 
- Missing of file .htaccess from file manager of 000Webhost.
- Re-factoring the logic of the if statements.
- Fixing code syntax.
- Change PHP version from the 000Webhost. 

Issue closed. Bug fixed.
