### ISSUE TITLE
Bug issue: Password prompt not informative enough. 

### ISSUE THREAD

**Issue by Patrick-Frendo** [Dame2Dolla/TechyDev#16]
Password complexity isn't mentioned.
![image](https://user-images.githubusercontent.com/16851267/235654155-f42c081d-86c0-482c-9f3b-293136104df3.png)

**Comment by Patrick-Frendo** [comment]
@claytonfarrugia  is this better? 
Password must be longer than 15 characters, must have Uppercase and Lowercase and AlphaNumeric with Special Characters.

**Comment by claytonfarrugia** [comment]
yes issue reported in our test case outcome and solution implemented .

**Comment by Patrick-Frendo** [comment]
Cool so changing this:
![image](https://user-images.githubusercontent.com/16851267/235654902-1998e263-4b0a-4bd3-ab18-e879361acf36.png)

To this:
![image](https://user-images.githubusercontent.com/16851267/235654957-fb56c842-658d-46dc-b526-f5be7a3b5f3c.png)
