### ISSUE TITLE
Bug Issue: "Remember me" function

### ISSUE THREAD

**Issue by Qlify** [Dame2Dolla/TechyDev#17]
The remember me function has a minor bug when being unselected and refreshing the page the box is selected again on its own.

To replicate this bug follow these steps:

Step 1: Check and then uncheck "remember me" box located in the login page
Step 2: Refresh the page the remember me check box will be checked again on its own.

**Comment by Patrick-Frendo** [comment]
Without screen shots i can not replicate the bug you are refering to.
Before refresh:
![image](https://user-images.githubusercontent.com/16851267/236206089-25afd7d6-aa31-4942-bd67-4435b0714477.png)

After Refresh:
![image](https://user-images.githubusercontent.com/16851267/236206155-769f1600-f40d-4022-8890-8f3fd6596f55.png)

Please provide further information, with screenshots and a more detailed step by step

**Comment by Qlify** [comment]
I think you can replicate this bug only in Google Chrome browser. I tried replicating it in another brewers this time "Opera GX" and the "remember me" function does not reset upon refresh and works as intended. If the bug is still not replicated from Google Chrome then its from my end.

**Comment by Patrick-Frendo** [comment]
Can you try private google chrome ?

**Comment by Qlify** [comment]
Sure

**Comment by Qlify** [comment]
It was indeed from my end I apologies.

**Comment by Patrick-Frendo** [comment]
no problem ticket closed.
