### ISSUE TITLE
Bug Issue: Search function personal Projects appear on other peoples profile.

### ISSUE THREAD

**Issue by Qlify** [Dame2Dolla/TechyDev#19]
Upon searching any user you will be redirected to their profile page but there is a bug,
where your personal projects will be displayed on their profile.

To replicate this bug:

Step 1: Create your project
Step 2: Search for a user in the search function for example you can search "c.farrugia@wlv.ac.uk" and you will see your personal projects on this persons profile.

**Comment by Patrick-Frendo** [comment]
Well done. Didn't notice this bug. 
![image](https://user-images.githubusercontent.com/16851267/236209483-0486cb7c-b6fd-45ac-95e8-66bff6791eba.png)
Will be fixing it shortly.

**Comment by Patrick-Frendo** [comment]
Bug fixed!
![image](https://user-images.githubusercontent.com/16851267/236210053-4fb60c80-c958-4c4b-8110-981af1c13790.png)

preview of site:
![image](https://user-images.githubusercontent.com/16851267/236210117-8fa7bfaa-0047-4aec-b8c6-d372130eb488.png)

**Comment by Qlify** [comment]
Thanks it works as intended now have a great day :D
