### ISSUE TITLE
Warning Message Showing when accessing our website. 

### ISSUE THREAD

**Issue by Patrick-Frendo** [Dame2Dolla/TechyDev#3]
Hey all, 
I noticed that the chrome is highlighting our website as suspicious. Anyone know what caused this? 

![image](https://user-images.githubusercontent.com/16851267/221349815-243ba7c2-d2cd-42a3-a59b-476885183673.png)

**Comment by Patrick-Frendo** [comment]
Thanks @claytonfarrugia for sharing the site to requestGoogle to remove the warning message. 
https://safebrowsing.google.com/safebrowsing/report_error/?hl=en

**Comment by claytonfarrugia** [comment]
welcome patrick, glad this issue was solved.

**Comment by Patrick-Frendo** [comment]
Ticket has been re-opened as the same problem has occured on the new domain name http://www.studentmind.xyz/
![image](https://user-images.githubusercontent.com/16851267/221971788-66720402-3474-4430-aeaa-16f2a20ed517.png)

please use the above link to settle this issue again. I'll close this issue once the warning message is gone.

**Comment by Patrick-Frendo** [comment]
![image](https://user-images.githubusercontent.com/16851267/221972651-771390da-1a73-4dc8-be5b-5a8fb21c2609.png)
Completed the form on my side. Best for other member to submit the form as well.

**Comment by Qlify** [comment]
Submitted it from my end :D
![image](https://user-images.githubusercontent.com/99338407/221991547-05dcfe41-8aed-4215-ae8b-2e3fc7592563.png)

**Comment by Dame2Dolla** [comment]
Submitted from my end also ^_^

**Comment by Patrick-Frendo** [comment]
Deceptive warning is message is gone. Well done guys Ticket closed.
