### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by Patrick-Frendo** [Dame2Dolla/TechyDev#6]
![image](https://user-images.githubusercontent.com/16851267/221425671-f8432879-f01e-4df6-bede-20dc9e96eb1e.png)

**Second error:** Failed to load resource: the server responded with a status of 404 ()

**Comment by claytonfarrugia** [comment]
this issue was fixed with the solution to the SSL certificate bug. check again please.

**Comment by Patrick-Frendo** [comment]
Added manifest.json file. Issue solved.
