### ISSUE TITLE
MyPHPAdmin root access denied.

### ISSUE THREAD

**Issue by Patrick-Frendo** [Dame2Dolla/TechyDev#9]
![image](https://user-images.githubusercontent.com/16851267/221427865-faae2ee9-acc9-4c7f-9c1a-a9a69dcd049f.png)

MyPHPAdmin doesn't allow root access to the company members. Can @Dame2Dolla have a look?

**Comment by claytonfarrugia** [comment]
i looked into this issue and noticed that an administrator from 000webhost mentioned in the [forum thread ](https://www.000webhost.com/forum/t/mysql-database-user-privileges/43838)that root privileges requires paid hosting services.

**Comment by Qlify** [comment]
Okay lets call the Data Analyst

**Comment by Patrick-Frendo** [comment]
Shall i close this issue ticket? since according to @claytonfarrugia  we are limited due to using a free service?

**Comment by Qlify** [comment]
Okay lets listen to our Cyber security professional :D

**Comment by Patrick-Frendo** [comment]
Think for this issue it is best to have a talk with @Dame2Dolla and @claytonfarrugia.

**Comment by claytonfarrugia** [comment]
executing such command requires elevated privileges which we dont have with our plan. issue closed.
